language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mdiazv/clean-architetris -f Dockerfile.dev .

script:
  - docker run mdiazv/clean-architetris go test -cover ./...
